// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$520 {

    static final FunctionDescriptor mmioRenameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRenameW$MH = RuntimeHelper.downcallHandle(
        "mmioRenameW",
        constants$520.mmioRenameW$FUNC
    );
    static final FunctionDescriptor mmioClose$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioClose$MH = RuntimeHelper.downcallHandle(
        "mmioClose",
        constants$520.mmioClose$FUNC
    );
    static final FunctionDescriptor mmioRead$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRead$MH = RuntimeHelper.downcallHandle(
        "mmioRead",
        constants$520.mmioRead$FUNC
    );
    static final FunctionDescriptor mmioWrite$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioWrite$MH = RuntimeHelper.downcallHandle(
        "mmioWrite",
        constants$520.mmioWrite$FUNC
    );
    static final FunctionDescriptor mmioSeek$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioSeek$MH = RuntimeHelper.downcallHandle(
        "mmioSeek",
        constants$520.mmioSeek$FUNC
    );
    static final FunctionDescriptor mmioGetInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioGetInfo$MH = RuntimeHelper.downcallHandle(
        "mmioGetInfo",
        constants$520.mmioGetInfo$FUNC
    );
}


