// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$812 {

    static final MemoryAddress X509_ECC_SIGNATURE$ADDR = MemoryAddress.ofLong(47L);
    static final MemoryAddress X942_DH_PARAMETERS$ADDR = MemoryAddress.ofLong(50L);
    static final MemoryAddress X509_BITS_WITHOUT_TRAILING_ZEROES$ADDR = MemoryAddress.ofLong(51L);
    static final MemoryAddress X942_OTHER_INFO$ADDR = MemoryAddress.ofLong(52L);
    static final MemoryAddress X509_CERT_PAIR$ADDR = MemoryAddress.ofLong(53L);
    static final MemoryAddress X509_ISSUING_DIST_POINT$ADDR = MemoryAddress.ofLong(54L);
}


