// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$402 {

    static final FunctionDescriptor WNetGetUniversalNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetUniversalNameW$MH = RuntimeHelper.downcallHandle(
        "WNetGetUniversalNameW",
        constants$402.WNetGetUniversalNameW$FUNC
    );
    static final FunctionDescriptor WNetGetUserA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetUserA$MH = RuntimeHelper.downcallHandle(
        "WNetGetUserA",
        constants$402.WNetGetUserA$FUNC
    );
    static final FunctionDescriptor WNetGetUserW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetUserW$MH = RuntimeHelper.downcallHandle(
        "WNetGetUserW",
        constants$402.WNetGetUserW$FUNC
    );
    static final FunctionDescriptor WNetGetProviderNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetProviderNameA$MH = RuntimeHelper.downcallHandle(
        "WNetGetProviderNameA",
        constants$402.WNetGetProviderNameA$FUNC
    );
    static final FunctionDescriptor WNetGetProviderNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetProviderNameW$MH = RuntimeHelper.downcallHandle(
        "WNetGetProviderNameW",
        constants$402.WNetGetProviderNameW$FUNC
    );
    static final FunctionDescriptor WNetGetNetworkInformationA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetNetworkInformationA$MH = RuntimeHelper.downcallHandle(
        "WNetGetNetworkInformationA",
        constants$402.WNetGetNetworkInformationA$FUNC
    );
}


