// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$536 {

    static final FunctionDescriptor SERVICE_MAIN_FUNCTIONA$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SERVICE_MAIN_FUNCTIONA$MH = RuntimeHelper.downcallHandle(
        constants$536.SERVICE_MAIN_FUNCTIONA$FUNC
    );
    static final FunctionDescriptor LPSERVICE_MAIN_FUNCTIONW$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LPSERVICE_MAIN_FUNCTIONW$MH = RuntimeHelper.downcallHandle(
        constants$536.LPSERVICE_MAIN_FUNCTIONW$FUNC
    );
    static final FunctionDescriptor LPSERVICE_MAIN_FUNCTIONA$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LPSERVICE_MAIN_FUNCTIONA$MH = RuntimeHelper.downcallHandle(
        constants$536.LPSERVICE_MAIN_FUNCTIONA$FUNC
    );
    static final FunctionDescriptor HANDLER_FUNCTION$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
}


