// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$174 {

    static final FunctionDescriptor GetCharWidth32A$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharWidth32A$MH = RuntimeHelper.downcallHandle(
        "GetCharWidth32A",
        constants$174.GetCharWidth32A$FUNC
    );
    static final FunctionDescriptor GetCharWidth32W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharWidth32W$MH = RuntimeHelper.downcallHandle(
        "GetCharWidth32W",
        constants$174.GetCharWidth32W$FUNC
    );
    static final FunctionDescriptor GetCharWidthFloatA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharWidthFloatA$MH = RuntimeHelper.downcallHandle(
        "GetCharWidthFloatA",
        constants$174.GetCharWidthFloatA$FUNC
    );
    static final FunctionDescriptor GetCharWidthFloatW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharWidthFloatW$MH = RuntimeHelper.downcallHandle(
        "GetCharWidthFloatW",
        constants$174.GetCharWidthFloatW$FUNC
    );
    static final FunctionDescriptor GetCharABCWidthsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharABCWidthsA$MH = RuntimeHelper.downcallHandle(
        "GetCharABCWidthsA",
        constants$174.GetCharABCWidthsA$FUNC
    );
    static final FunctionDescriptor GetCharABCWidthsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCharABCWidthsW$MH = RuntimeHelper.downcallHandle(
        "GetCharABCWidthsW",
        constants$174.GetCharABCWidthsW$FUNC
    );
}


