// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$394 {

    static final FunctionDescriptor RegLoadAppKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegLoadAppKeyA$MH = RuntimeHelper.downcallHandle(
        "RegLoadAppKeyA",
        constants$394.RegLoadAppKeyA$FUNC
    );
    static final FunctionDescriptor RegLoadAppKeyW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegLoadAppKeyW$MH = RuntimeHelper.downcallHandle(
        "RegLoadAppKeyW",
        constants$394.RegLoadAppKeyW$FUNC
    );
    static final FunctionDescriptor InitiateSystemShutdownA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle InitiateSystemShutdownA$MH = RuntimeHelper.downcallHandle(
        "InitiateSystemShutdownA",
        constants$394.InitiateSystemShutdownA$FUNC
    );
    static final FunctionDescriptor InitiateSystemShutdownW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle InitiateSystemShutdownW$MH = RuntimeHelper.downcallHandle(
        "InitiateSystemShutdownW",
        constants$394.InitiateSystemShutdownW$FUNC
    );
    static final FunctionDescriptor AbortSystemShutdownA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AbortSystemShutdownA$MH = RuntimeHelper.downcallHandle(
        "AbortSystemShutdownA",
        constants$394.AbortSystemShutdownA$FUNC
    );
    static final FunctionDescriptor AbortSystemShutdownW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AbortSystemShutdownW$MH = RuntimeHelper.downcallHandle(
        "AbortSystemShutdownW",
        constants$394.AbortSystemShutdownW$FUNC
    );
}


