// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$351 {

    static final FunctionDescriptor LOCALE_ENUMPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LOCALE_ENUMPROCW$MH = RuntimeHelper.downcallHandle(
        constants$351.LOCALE_ENUMPROCW$FUNC
    );
    static final FunctionDescriptor LANGUAGEGROUP_ENUMPROCA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LANGUAGEGROUP_ENUMPROCA$MH = RuntimeHelper.downcallHandle(
        constants$351.LANGUAGEGROUP_ENUMPROCA$FUNC
    );
    static final FunctionDescriptor LANGGROUPLOCALE_ENUMPROCA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LANGGROUPLOCALE_ENUMPROCA$MH = RuntimeHelper.downcallHandle(
        constants$351.LANGGROUPLOCALE_ENUMPROCA$FUNC
    );
}


