// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$625 {

    static final FunctionDescriptor CryptUninstallCancelRetrieval$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptUninstallCancelRetrieval$MH = RuntimeHelper.downcallHandle(
        "CryptUninstallCancelRetrieval",
        constants$625.CryptUninstallCancelRetrieval$FUNC
    );
    static final FunctionDescriptor CryptCancelAsyncRetrieval$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptCancelAsyncRetrieval$MH = RuntimeHelper.downcallHandle(
        "CryptCancelAsyncRetrieval",
        constants$625.CryptCancelAsyncRetrieval$FUNC
    );
    static final FunctionDescriptor PFN_CRYPT_ASYNC_RETRIEVAL_COMPLETION_FUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CRYPT_ASYNC_RETRIEVAL_COMPLETION_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$625.PFN_CRYPT_ASYNC_RETRIEVAL_COMPLETION_FUNC$FUNC
    );
    static final FunctionDescriptor PFN_CANCEL_ASYNC_RETRIEVAL_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CANCEL_ASYNC_RETRIEVAL_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$625.PFN_CANCEL_ASYNC_RETRIEVAL_FUNC$FUNC
    );
}


