// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$885 {

    static final MemoryAddress CREDENTIAL_OID_PASSWORD_CREDENTIALS_A$ADDR = MemoryAddress.ofLong(1L);
    static final MemoryAddress CREDENTIAL_OID_PASSWORD_CREDENTIALS_W$ADDR = MemoryAddress.ofLong(2L);
    static final MemoryAddress CREDENTIAL_OID_PASSWORD_CREDENTIALS$ADDR = MemoryAddress.ofLong(1L);
    static final MemorySegment SCHEME_OID_RETRIEVE_ENCODED_OBJECT_FUNC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SchemeDllRetrieveEncodedObject");
    static final MemorySegment SCHEME_OID_RETRIEVE_ENCODED_OBJECTW_FUNC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SchemeDllRetrieveEncodedObjectW");
    static final MemorySegment CONTEXT_OID_CREATE_OBJECT_CONTEXT_FUNC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ContextDllCreateObjectContext");
}


