// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$244 {

    static final FunctionDescriptor SendMessageCallbackW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SendMessageCallbackW$MH = RuntimeHelper.downcallHandle(
        "SendMessageCallbackW",
        constants$244.SendMessageCallbackW$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageExA$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageExA",
        constants$244.BroadcastSystemMessageExA$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageExW$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageExW",
        constants$244.BroadcastSystemMessageExW$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageA$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageA",
        constants$244.BroadcastSystemMessageA$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageW$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageW",
        constants$244.BroadcastSystemMessageW$FUNC
    );
    static final FunctionDescriptor RegisterDeviceNotificationA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterDeviceNotificationA$MH = RuntimeHelper.downcallHandle(
        "RegisterDeviceNotificationA",
        constants$244.RegisterDeviceNotificationA$FUNC
    );
}


