// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$98 {

    static final FunctionDescriptor HeapReAlloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle HeapReAlloc$MH = RuntimeHelper.downcallHandle(
        "HeapReAlloc",
        constants$98.HeapReAlloc$FUNC
    );
    static final FunctionDescriptor HeapFree$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HeapFree$MH = RuntimeHelper.downcallHandle(
        "HeapFree",
        constants$98.HeapFree$FUNC
    );
    static final FunctionDescriptor HeapSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HeapSize$MH = RuntimeHelper.downcallHandle(
        "HeapSize",
        constants$98.HeapSize$FUNC
    );
    static final FunctionDescriptor GetProcessHeap$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetProcessHeap$MH = RuntimeHelper.downcallHandle(
        "GetProcessHeap",
        constants$98.GetProcessHeap$FUNC
    );
    static final FunctionDescriptor HeapCompact$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle HeapCompact$MH = RuntimeHelper.downcallHandle(
        "HeapCompact",
        constants$98.HeapCompact$FUNC
    );
    static final FunctionDescriptor HeapSetInformation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle HeapSetInformation$MH = RuntimeHelper.downcallHandle(
        "HeapSetInformation",
        constants$98.HeapSetInformation$FUNC
    );
}


