// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$460 {

    static final FunctionDescriptor UILANGUAGE_ENUMPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle UILANGUAGE_ENUMPROCW$MH = RuntimeHelper.downcallHandle(
        constants$460.UILANGUAGE_ENUMPROCW$FUNC
    );
    static final FunctionDescriptor CODEPAGE_ENUMPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CODEPAGE_ENUMPROCW$MH = RuntimeHelper.downcallHandle(
        constants$460.CODEPAGE_ENUMPROCW$FUNC
    );
    static final FunctionDescriptor DATEFMT_ENUMPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DATEFMT_ENUMPROCW$MH = RuntimeHelper.downcallHandle(
        constants$460.DATEFMT_ENUMPROCW$FUNC
    );
}


