// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$543 {

    static final FunctionDescriptor QueryServiceConfig2A$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceConfig2A$MH = RuntimeHelper.downcallHandle(
        "QueryServiceConfig2A",
        constants$543.QueryServiceConfig2A$FUNC
    );
    static final FunctionDescriptor QueryServiceConfig2W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceConfig2W$MH = RuntimeHelper.downcallHandle(
        "QueryServiceConfig2W",
        constants$543.QueryServiceConfig2W$FUNC
    );
    static final FunctionDescriptor QueryServiceLockStatusA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceLockStatusA$MH = RuntimeHelper.downcallHandle(
        "QueryServiceLockStatusA",
        constants$543.QueryServiceLockStatusA$FUNC
    );
    static final FunctionDescriptor QueryServiceLockStatusW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceLockStatusW$MH = RuntimeHelper.downcallHandle(
        "QueryServiceLockStatusW",
        constants$543.QueryServiceLockStatusW$FUNC
    );
    static final FunctionDescriptor QueryServiceObjectSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceObjectSecurity$MH = RuntimeHelper.downcallHandle(
        "QueryServiceObjectSecurity",
        constants$543.QueryServiceObjectSecurity$FUNC
    );
    static final FunctionDescriptor QueryServiceStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceStatus$MH = RuntimeHelper.downcallHandle(
        "QueryServiceStatus",
        constants$543.QueryServiceStatus$FUNC
    );
}


