// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$651 {

    static final FunctionDescriptor SCardSetCardTypeProviderNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardSetCardTypeProviderNameA$MH = RuntimeHelper.downcallHandle(
        "SCardSetCardTypeProviderNameA",
        constants$651.SCardSetCardTypeProviderNameA$FUNC
    );
    static final FunctionDescriptor SCardSetCardTypeProviderNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardSetCardTypeProviderNameW$MH = RuntimeHelper.downcallHandle(
        "SCardSetCardTypeProviderNameW",
        constants$651.SCardSetCardTypeProviderNameW$FUNC
    );
    static final FunctionDescriptor SCardForgetCardTypeA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardForgetCardTypeA$MH = RuntimeHelper.downcallHandle(
        "SCardForgetCardTypeA",
        constants$651.SCardForgetCardTypeA$FUNC
    );
    static final FunctionDescriptor SCardForgetCardTypeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardForgetCardTypeW$MH = RuntimeHelper.downcallHandle(
        "SCardForgetCardTypeW",
        constants$651.SCardForgetCardTypeW$FUNC
    );
    static final FunctionDescriptor SCardFreeMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardFreeMemory$MH = RuntimeHelper.downcallHandle(
        "SCardFreeMemory",
        constants$651.SCardFreeMemory$FUNC
    );
    static final FunctionDescriptor SCardAccessStartedEvent$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle SCardAccessStartedEvent$MH = RuntimeHelper.downcallHandle(
        "SCardAccessStartedEvent",
        constants$651.SCardAccessStartedEvent$FUNC
    );
}


