// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$305 {

    static final FunctionDescriptor GetWinMetaFileBits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWinMetaFileBits$MH = RuntimeHelper.downcallHandle(
        "GetWinMetaFileBits",
        constants$305.GetWinMetaFileBits$FUNC
    );
    static final FunctionDescriptor PlayEnhMetaFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PlayEnhMetaFile$MH = RuntimeHelper.downcallHandle(
        "PlayEnhMetaFile",
        constants$305.PlayEnhMetaFile$FUNC
    );
    static final FunctionDescriptor PlayEnhMetaFileRecord$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PlayEnhMetaFileRecord$MH = RuntimeHelper.downcallHandle(
        "PlayEnhMetaFileRecord",
        constants$305.PlayEnhMetaFileRecord$FUNC
    );
    static final FunctionDescriptor SetEnhMetaFileBits$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetEnhMetaFileBits$MH = RuntimeHelper.downcallHandle(
        "SetEnhMetaFileBits",
        constants$305.SetEnhMetaFileBits$FUNC
    );
    static final FunctionDescriptor SetWinMetaFileBits$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetWinMetaFileBits$MH = RuntimeHelper.downcallHandle(
        "SetWinMetaFileBits",
        constants$305.SetWinMetaFileBits$FUNC
    );
    static final FunctionDescriptor GdiComment$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GdiComment$MH = RuntimeHelper.downcallHandle(
        "GdiComment",
        constants$305.GdiComment$FUNC
    );
}


