// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$245 {

    static final FunctionDescriptor RegisterDeviceNotificationW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterDeviceNotificationW$MH = RuntimeHelper.downcallHandle(
        "RegisterDeviceNotificationW",
        constants$245.RegisterDeviceNotificationW$FUNC
    );
    static final FunctionDescriptor UnregisterDeviceNotification$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnregisterDeviceNotification$MH = RuntimeHelper.downcallHandle(
        "UnregisterDeviceNotification",
        constants$245.UnregisterDeviceNotification$FUNC
    );
    static final FunctionDescriptor RegisterPowerSettingNotification$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterPowerSettingNotification$MH = RuntimeHelper.downcallHandle(
        "RegisterPowerSettingNotification",
        constants$245.RegisterPowerSettingNotification$FUNC
    );
    static final FunctionDescriptor UnregisterPowerSettingNotification$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnregisterPowerSettingNotification$MH = RuntimeHelper.downcallHandle(
        "UnregisterPowerSettingNotification",
        constants$245.UnregisterPowerSettingNotification$FUNC
    );
    static final FunctionDescriptor RegisterSuspendResumeNotification$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterSuspendResumeNotification$MH = RuntimeHelper.downcallHandle(
        "RegisterSuspendResumeNotification",
        constants$245.RegisterSuspendResumeNotification$FUNC
    );
    static final FunctionDescriptor UnregisterSuspendResumeNotification$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnregisterSuspendResumeNotification$MH = RuntimeHelper.downcallHandle(
        "UnregisterSuspendResumeNotification",
        constants$245.UnregisterSuspendResumeNotification$FUNC
    );
}


