// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$407 {

    static final FunctionDescriptor EnumPropsExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumPropsExW$MH = RuntimeHelper.downcallHandle(
        "EnumPropsExW",
        constants$407.EnumPropsExW$FUNC
    );
    static final FunctionDescriptor EnumPropsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EnumPropsA$MH = RuntimeHelper.downcallHandle(
        "EnumPropsA",
        constants$407.EnumPropsA$FUNC
    );
    static final FunctionDescriptor EnumPropsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EnumPropsW$MH = RuntimeHelper.downcallHandle(
        "EnumPropsW",
        constants$407.EnumPropsW$FUNC
    );
    static final FunctionDescriptor SetWindowTextA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetWindowTextA$MH = RuntimeHelper.downcallHandle(
        "SetWindowTextA",
        constants$407.SetWindowTextA$FUNC
    );
    static final FunctionDescriptor SetWindowTextW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetWindowTextW$MH = RuntimeHelper.downcallHandle(
        "SetWindowTextW",
        constants$407.SetWindowTextW$FUNC
    );
    static final FunctionDescriptor GetWindowTextA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetWindowTextA$MH = RuntimeHelper.downcallHandle(
        "GetWindowTextA",
        constants$407.GetWindowTextA$FUNC
    );
}


