// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$282 {

    static final FunctionDescriptor GetObjectType$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetObjectType$MH = RuntimeHelper.downcallHandle(
        "GetObjectType",
        constants$282.GetObjectType$FUNC
    );
    static final FunctionDescriptor GetOutlineTextMetricsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetOutlineTextMetricsA$MH = RuntimeHelper.downcallHandle(
        "GetOutlineTextMetricsA",
        constants$282.GetOutlineTextMetricsA$FUNC
    );
    static final FunctionDescriptor GetOutlineTextMetricsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetOutlineTextMetricsW$MH = RuntimeHelper.downcallHandle(
        "GetOutlineTextMetricsW",
        constants$282.GetOutlineTextMetricsW$FUNC
    );
    static final FunctionDescriptor GetPaletteEntries$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPaletteEntries$MH = RuntimeHelper.downcallHandle(
        "GetPaletteEntries",
        constants$282.GetPaletteEntries$FUNC
    );
    static final FunctionDescriptor GetPixel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetPixel$MH = RuntimeHelper.downcallHandle(
        "GetPixel",
        constants$282.GetPixel$FUNC
    );
    static final FunctionDescriptor GetPixelFormat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPixelFormat$MH = RuntimeHelper.downcallHandle(
        "GetPixelFormat",
        constants$282.GetPixelFormat$FUNC
    );
}


