// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$167 {

    static final FunctionDescriptor IsWellKnownSid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle IsWellKnownSid$MH = RuntimeHelper.downcallHandle(
        "IsWellKnownSid",
        constants$167.IsWellKnownSid$FUNC
    );
    static final FunctionDescriptor MakeAbsoluteSD$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MakeAbsoluteSD$MH = RuntimeHelper.downcallHandle(
        "MakeAbsoluteSD",
        constants$167.MakeAbsoluteSD$FUNC
    );
    static final FunctionDescriptor MakeSelfRelativeSD$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MakeSelfRelativeSD$MH = RuntimeHelper.downcallHandle(
        "MakeSelfRelativeSD",
        constants$167.MakeSelfRelativeSD$FUNC
    );
    static final FunctionDescriptor MapGenericMask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MapGenericMask$MH = RuntimeHelper.downcallHandle(
        "MapGenericMask",
        constants$167.MapGenericMask$FUNC
    );
    static final FunctionDescriptor ObjectCloseAuditAlarmW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ObjectCloseAuditAlarmW$MH = RuntimeHelper.downcallHandle(
        "ObjectCloseAuditAlarmW",
        constants$167.ObjectCloseAuditAlarmW$FUNC
    );
    static final FunctionDescriptor ObjectDeleteAuditAlarmW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ObjectDeleteAuditAlarmW$MH = RuntimeHelper.downcallHandle(
        "ObjectDeleteAuditAlarmW",
        constants$167.ObjectDeleteAuditAlarmW$FUNC
    );
}


