// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$367 {

    static final FunctionDescriptor GetClipboardData$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetClipboardData$MH = RuntimeHelper.downcallHandle(
        "GetClipboardData",
        constants$367.GetClipboardData$FUNC
    );
    static final FunctionDescriptor RegisterClipboardFormatA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterClipboardFormatA$MH = RuntimeHelper.downcallHandle(
        "RegisterClipboardFormatA",
        constants$367.RegisterClipboardFormatA$FUNC
    );
    static final FunctionDescriptor RegisterClipboardFormatW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterClipboardFormatW$MH = RuntimeHelper.downcallHandle(
        "RegisterClipboardFormatW",
        constants$367.RegisterClipboardFormatW$FUNC
    );
    static final FunctionDescriptor CountClipboardFormats$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CountClipboardFormats$MH = RuntimeHelper.downcallHandle(
        "CountClipboardFormats",
        constants$367.CountClipboardFormats$FUNC
    );
    static final FunctionDescriptor EnumClipboardFormats$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumClipboardFormats$MH = RuntimeHelper.downcallHandle(
        "EnumClipboardFormats",
        constants$367.EnumClipboardFormats$FUNC
    );
    static final FunctionDescriptor GetClipboardFormatNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetClipboardFormatNameA$MH = RuntimeHelper.downcallHandle(
        "GetClipboardFormatNameA",
        constants$367.GetClipboardFormatNameA$FUNC
    );
}


