// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$345 {

    static final FunctionDescriptor UserHandleGrantAccess$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle UserHandleGrantAccess$MH = RuntimeHelper.downcallHandle(
        "UserHandleGrantAccess",
        constants$345.UserHandleGrantAccess$FUNC
    );
    static final FunctionDescriptor GetRawInputData$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetRawInputData$MH = RuntimeHelper.downcallHandle(
        "GetRawInputData",
        constants$345.GetRawInputData$FUNC
    );
    static final FunctionDescriptor GetRawInputDeviceInfoA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetRawInputDeviceInfoA$MH = RuntimeHelper.downcallHandle(
        "GetRawInputDeviceInfoA",
        constants$345.GetRawInputDeviceInfoA$FUNC
    );
    static final FunctionDescriptor GetRawInputDeviceInfoW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetRawInputDeviceInfoW$MH = RuntimeHelper.downcallHandle(
        "GetRawInputDeviceInfoW",
        constants$345.GetRawInputDeviceInfoW$FUNC
    );
    static final FunctionDescriptor GetRawInputBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetRawInputBuffer$MH = RuntimeHelper.downcallHandle(
        "GetRawInputBuffer",
        constants$345.GetRawInputBuffer$FUNC
    );
    static final FunctionDescriptor RegisterRawInputDevices$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterRawInputDevices$MH = RuntimeHelper.downcallHandle(
        "RegisterRawInputDevices",
        constants$345.RegisterRawInputDevices$FUNC
    );
}


