// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor _bittest64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _bittest64$MH = RuntimeHelper.downcallHandle(
        "_bittest64",
        constants$3._bittest64$FUNC
    );
    static final FunctionDescriptor _bittestandcomplement64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _bittestandcomplement64$MH = RuntimeHelper.downcallHandle(
        "_bittestandcomplement64",
        constants$3._bittestandcomplement64$FUNC
    );
    static final FunctionDescriptor _bittestandset64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _bittestandset64$MH = RuntimeHelper.downcallHandle(
        "_bittestandset64",
        constants$3._bittestandset64$FUNC
    );
    static final FunctionDescriptor _bittestandreset64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _bittestandreset64$MH = RuntimeHelper.downcallHandle(
        "_bittestandreset64",
        constants$3._bittestandreset64$FUNC
    );
    static final FunctionDescriptor _interlockedbittestandset64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _interlockedbittestandset64$MH = RuntimeHelper.downcallHandle(
        "_interlockedbittestandset64",
        constants$3._interlockedbittestandset64$FUNC
    );
    static final FunctionDescriptor _interlockedbittestandreset64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _interlockedbittestandreset64$MH = RuntimeHelper.downcallHandle(
        "_interlockedbittestandreset64",
        constants$3._interlockedbittestandreset64$FUNC
    );
}


