// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$146 {

    static final FunctionDescriptor DeleteEnclave$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeleteEnclave$MH = RuntimeHelper.downcallHandle(
        "DeleteEnclave",
        constants$146.DeleteEnclave$FUNC
    );
    static final FunctionDescriptor IsProcessInJob$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IsProcessInJob$MH = RuntimeHelper.downcallHandle(
        "IsProcessInJob",
        constants$146.IsProcessInJob$FUNC
    );
    static final FunctionDescriptor ENUMRESLANGPROCA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ENUMRESLANGPROCA$MH = RuntimeHelper.downcallHandle(
        constants$146.ENUMRESLANGPROCA$FUNC
    );
    static final FunctionDescriptor ENUMRESLANGPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ENUMRESLANGPROCW$MH = RuntimeHelper.downcallHandle(
        constants$146.ENUMRESLANGPROCW$FUNC
    );
}


