// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$499 {

    static final FunctionDescriptor RegRenameKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegRenameKey$MH = RuntimeHelper.downcallHandle(
        "RegRenameKey",
        constants$499.RegRenameKey$FUNC
    );
    static final FunctionDescriptor RegSaveKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegSaveKeyA$MH = RuntimeHelper.downcallHandle(
        "RegSaveKeyA",
        constants$499.RegSaveKeyA$FUNC
    );
    static final FunctionDescriptor RegSaveKeyW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegSaveKeyW$MH = RuntimeHelper.downcallHandle(
        "RegSaveKeyW",
        constants$499.RegSaveKeyW$FUNC
    );
    static final FunctionDescriptor RegSetKeySecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegSetKeySecurity$MH = RuntimeHelper.downcallHandle(
        "RegSetKeySecurity",
        constants$499.RegSetKeySecurity$FUNC
    );
    static final FunctionDescriptor RegSetValueA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegSetValueA$MH = RuntimeHelper.downcallHandle(
        "RegSetValueA",
        constants$499.RegSetValueA$FUNC
    );
    static final FunctionDescriptor RegSetValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegSetValueW$MH = RuntimeHelper.downcallHandle(
        "RegSetValueW",
        constants$499.RegSetValueW$FUNC
    );
}


