// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$734 {

    static final MemoryAddress RT_ACCELERATOR$ADDR = MemoryAddress.ofLong(9L);
    static final MemoryAddress RT_RCDATA$ADDR = MemoryAddress.ofLong(10L);
    static final MemoryAddress RT_MESSAGETABLE$ADDR = MemoryAddress.ofLong(11L);
    static final MemoryAddress RT_GROUP_CURSOR$ADDR = MemoryAddress.ofLong(12L);
    static final MemoryAddress RT_GROUP_ICON$ADDR = MemoryAddress.ofLong(14L);
    static final MemoryAddress RT_VERSION$ADDR = MemoryAddress.ofLong(16L);
}


