// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$13 {

    static final FunctionDescriptor WriteUCharRelease$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WriteUCharRelease$MH = RuntimeHelper.downcallHandle(
        "WriteUCharRelease",
        constants$13.WriteUCharRelease$FUNC
    );
    static final FunctionDescriptor WriteUCharNoFence$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WriteUCharNoFence$MH = RuntimeHelper.downcallHandle(
        "WriteUCharNoFence",
        constants$13.WriteUCharNoFence$FUNC
    );
    static final FunctionDescriptor WriteBooleanRelease$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WriteBooleanRelease$MH = RuntimeHelper.downcallHandle(
        "WriteBooleanRelease",
        constants$13.WriteBooleanRelease$FUNC
    );
    static final FunctionDescriptor WriteBooleanNoFence$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WriteBooleanNoFence$MH = RuntimeHelper.downcallHandle(
        "WriteBooleanNoFence",
        constants$13.WriteBooleanNoFence$FUNC
    );
    static final FunctionDescriptor WriteUCharRaw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WriteUCharRaw$MH = RuntimeHelper.downcallHandle(
        "WriteUCharRaw",
        constants$13.WriteUCharRaw$FUNC
    );
    static final FunctionDescriptor ReadUShortAcquire$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReadUShortAcquire$MH = RuntimeHelper.downcallHandle(
        "ReadUShortAcquire",
        constants$13.ReadUShortAcquire$FUNC
    );
}


