// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$575 {

    static final FunctionDescriptor CryptInitOIDFunctionSet$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptInitOIDFunctionSet$MH = RuntimeHelper.downcallHandle(
        "CryptInitOIDFunctionSet",
        constants$575.CryptInitOIDFunctionSet$FUNC
    );
    static final FunctionDescriptor CryptGetOIDFunctionAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptGetOIDFunctionAddress$MH = RuntimeHelper.downcallHandle(
        "CryptGetOIDFunctionAddress",
        constants$575.CryptGetOIDFunctionAddress$FUNC
    );
    static final FunctionDescriptor CryptGetDefaultOIDDllList$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptGetDefaultOIDDllList$MH = RuntimeHelper.downcallHandle(
        "CryptGetDefaultOIDDllList",
        constants$575.CryptGetDefaultOIDDllList$FUNC
    );
    static final FunctionDescriptor CryptGetDefaultOIDFunctionAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptGetDefaultOIDFunctionAddress$MH = RuntimeHelper.downcallHandle(
        "CryptGetDefaultOIDFunctionAddress",
        constants$575.CryptGetDefaultOIDFunctionAddress$FUNC
    );
    static final FunctionDescriptor CryptFreeOIDFunctionAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptFreeOIDFunctionAddress$MH = RuntimeHelper.downcallHandle(
        "CryptFreeOIDFunctionAddress",
        constants$575.CryptFreeOIDFunctionAddress$FUNC
    );
    static final FunctionDescriptor CryptRegisterOIDFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptRegisterOIDFunction$MH = RuntimeHelper.downcallHandle(
        "CryptRegisterOIDFunction",
        constants$575.CryptRegisterOIDFunction$FUNC
    );
}


