// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$476 {

    static final FunctionDescriptor EnumSystemLanguageGroupsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumSystemLanguageGroupsA$MH = RuntimeHelper.downcallHandle(
        "EnumSystemLanguageGroupsA",
        constants$476.EnumSystemLanguageGroupsA$FUNC
    );
    static final FunctionDescriptor EnumSystemLanguageGroupsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumSystemLanguageGroupsW$MH = RuntimeHelper.downcallHandle(
        "EnumSystemLanguageGroupsW",
        constants$476.EnumSystemLanguageGroupsW$FUNC
    );
    static final FunctionDescriptor EnumLanguageGroupLocalesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumLanguageGroupLocalesA$MH = RuntimeHelper.downcallHandle(
        "EnumLanguageGroupLocalesA",
        constants$476.EnumLanguageGroupLocalesA$FUNC
    );
    static final FunctionDescriptor EnumLanguageGroupLocalesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumLanguageGroupLocalesW$MH = RuntimeHelper.downcallHandle(
        "EnumLanguageGroupLocalesW",
        constants$476.EnumLanguageGroupLocalesW$FUNC
    );
    static final FunctionDescriptor EnumUILanguagesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumUILanguagesA$MH = RuntimeHelper.downcallHandle(
        "EnumUILanguagesA",
        constants$476.EnumUILanguagesA$FUNC
    );
    static final FunctionDescriptor EnumUILanguagesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumUILanguagesW$MH = RuntimeHelper.downcallHandle(
        "EnumUILanguagesW",
        constants$476.EnumUILanguagesW$FUNC
    );
}


