// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$268 {

    static final FunctionDescriptor CharLowerBuffW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CharLowerBuffW$MH = RuntimeHelper.downcallHandle(
        "CharLowerBuffW",
        constants$268.CharLowerBuffW$FUNC
    );
    static final FunctionDescriptor CharNextA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharNextA$MH = RuntimeHelper.downcallHandle(
        "CharNextA",
        constants$268.CharNextA$FUNC
    );
    static final FunctionDescriptor CharNextW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharNextW$MH = RuntimeHelper.downcallHandle(
        "CharNextW",
        constants$268.CharNextW$FUNC
    );
    static final FunctionDescriptor CharPrevA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharPrevA$MH = RuntimeHelper.downcallHandle(
        "CharPrevA",
        constants$268.CharPrevA$FUNC
    );
    static final FunctionDescriptor CharPrevW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharPrevW$MH = RuntimeHelper.downcallHandle(
        "CharPrevW",
        constants$268.CharPrevW$FUNC
    );
    static final FunctionDescriptor CharNextExA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CharNextExA$MH = RuntimeHelper.downcallHandle(
        "CharNextExA",
        constants$268.CharNextExA$FUNC
    );
}


