// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$273 {

    static final FunctionDescriptor Ellipse$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Ellipse$MH = RuntimeHelper.downcallHandle(
        "Ellipse",
        constants$273.Ellipse$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesExA$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesExA",
        constants$273.EnumFontFamiliesExA$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesExW$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesExW",
        constants$273.EnumFontFamiliesExW$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesA$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesA",
        constants$273.EnumFontFamiliesA$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesW$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesW",
        constants$273.EnumFontFamiliesW$FUNC
    );
    static final FunctionDescriptor EnumFontsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontsA$MH = RuntimeHelper.downcallHandle(
        "EnumFontsA",
        constants$273.EnumFontsA$FUNC
    );
}


