// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$519 {

    static final FunctionDescriptor mmioStringToFOURCCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioStringToFOURCCW$MH = RuntimeHelper.downcallHandle(
        "mmioStringToFOURCCW",
        constants$519.mmioStringToFOURCCW$FUNC
    );
    static final FunctionDescriptor mmioInstallIOProcA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioInstallIOProcA$MH = RuntimeHelper.downcallHandle(
        "mmioInstallIOProcA",
        constants$519.mmioInstallIOProcA$FUNC
    );
    static final FunctionDescriptor mmioInstallIOProcW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioInstallIOProcW$MH = RuntimeHelper.downcallHandle(
        "mmioInstallIOProcW",
        constants$519.mmioInstallIOProcW$FUNC
    );
    static final FunctionDescriptor mmioOpenA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioOpenA$MH = RuntimeHelper.downcallHandle(
        "mmioOpenA",
        constants$519.mmioOpenA$FUNC
    );
    static final FunctionDescriptor mmioOpenW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioOpenW$MH = RuntimeHelper.downcallHandle(
        "mmioOpenW",
        constants$519.mmioOpenW$FUNC
    );
    static final FunctionDescriptor mmioRenameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRenameA$MH = RuntimeHelper.downcallHandle(
        "mmioRenameA",
        constants$519.mmioRenameA$FUNC
    );
}


