// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$369 {

    static final FunctionDescriptor RemoveClipboardFormatListener$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveClipboardFormatListener$MH = RuntimeHelper.downcallHandle(
        "RemoveClipboardFormatListener",
        constants$369.RemoveClipboardFormatListener$FUNC
    );
    static final FunctionDescriptor GetUpdatedClipboardFormats$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetUpdatedClipboardFormats$MH = RuntimeHelper.downcallHandle(
        "GetUpdatedClipboardFormats",
        constants$369.GetUpdatedClipboardFormats$FUNC
    );
    static final FunctionDescriptor CharToOemA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharToOemA$MH = RuntimeHelper.downcallHandle(
        "CharToOemA",
        constants$369.CharToOemA$FUNC
    );
    static final FunctionDescriptor CharToOemW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharToOemW$MH = RuntimeHelper.downcallHandle(
        "CharToOemW",
        constants$369.CharToOemW$FUNC
    );
    static final FunctionDescriptor OemToCharA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OemToCharA$MH = RuntimeHelper.downcallHandle(
        "OemToCharA",
        constants$369.OemToCharA$FUNC
    );
    static final FunctionDescriptor OemToCharW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OemToCharW$MH = RuntimeHelper.downcallHandle(
        "OemToCharW",
        constants$369.OemToCharW$FUNC
    );
}


