// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$190 {

    static final FunctionDescriptor RemoveFontResourceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveFontResourceA$MH = RuntimeHelper.downcallHandle(
        "RemoveFontResourceA",
        constants$190.RemoveFontResourceA$FUNC
    );
    static final FunctionDescriptor RemoveFontResourceW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveFontResourceW$MH = RuntimeHelper.downcallHandle(
        "RemoveFontResourceW",
        constants$190.RemoveFontResourceW$FUNC
    );
    static final FunctionDescriptor RoundRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RoundRect$MH = RuntimeHelper.downcallHandle(
        "RoundRect",
        constants$190.RoundRect$FUNC
    );
    static final FunctionDescriptor ResizePalette$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ResizePalette$MH = RuntimeHelper.downcallHandle(
        "ResizePalette",
        constants$190.ResizePalette$FUNC
    );
    static final FunctionDescriptor SaveDC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SaveDC$MH = RuntimeHelper.downcallHandle(
        "SaveDC",
        constants$190.SaveDC$FUNC
    );
    static final FunctionDescriptor SelectClipRgn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SelectClipRgn$MH = RuntimeHelper.downcallHandle(
        "SelectClipRgn",
        constants$190.SelectClipRgn$FUNC
    );
}


