// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$185 {

    static final FunctionDescriptor SetThreadAffinityMask$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SetThreadAffinityMask$MH = RuntimeHelper.downcallHandle(
        "SetThreadAffinityMask",
        constants$185.SetThreadAffinityMask$FUNC
    );
    static final FunctionDescriptor SetProcessDEPPolicy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetProcessDEPPolicy$MH = RuntimeHelper.downcallHandle(
        "SetProcessDEPPolicy",
        constants$185.SetProcessDEPPolicy$FUNC
    );
    static final FunctionDescriptor GetProcessDEPPolicy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetProcessDEPPolicy$MH = RuntimeHelper.downcallHandle(
        "GetProcessDEPPolicy",
        constants$185.GetProcessDEPPolicy$FUNC
    );
    static final FunctionDescriptor RequestWakeupLatency$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RequestWakeupLatency$MH = RuntimeHelper.downcallHandle(
        "RequestWakeupLatency",
        constants$185.RequestWakeupLatency$FUNC
    );
    static final FunctionDescriptor IsSystemResumeAutomatic$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle IsSystemResumeAutomatic$MH = RuntimeHelper.downcallHandle(
        "IsSystemResumeAutomatic",
        constants$185.IsSystemResumeAutomatic$FUNC
    );
    static final FunctionDescriptor GetThreadSelectorEntry$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetThreadSelectorEntry$MH = RuntimeHelper.downcallHandle(
        "GetThreadSelectorEntry",
        constants$185.GetThreadSelectorEntry$FUNC
    );
}


