// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$215 {

    static final FunctionDescriptor GdiSetBatchLimit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GdiSetBatchLimit$MH = RuntimeHelper.downcallHandle(
        "GdiSetBatchLimit",
        constants$215.GdiSetBatchLimit$FUNC
    );
    static final FunctionDescriptor GdiGetBatchLimit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle GdiGetBatchLimit$MH = RuntimeHelper.downcallHandle(
        "GdiGetBatchLimit",
        constants$215.GdiGetBatchLimit$FUNC
    );
    static final FunctionDescriptor ICMENUMPROCA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ICMENUMPROCA$MH = RuntimeHelper.downcallHandle(
        constants$215.ICMENUMPROCA$FUNC
    );
    static final FunctionDescriptor ICMENUMPROCW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ICMENUMPROCW$MH = RuntimeHelper.downcallHandle(
        constants$215.ICMENUMPROCW$FUNC
    );
}


