// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$76 {

    static final FunctionDescriptor FindNextFileW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindNextFileW$MH = RuntimeHelper.downcallHandle(
        "FindNextFileW",
        constants$76.FindNextFileW$FUNC
    );
    static final FunctionDescriptor FindNextVolumeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle FindNextVolumeW$MH = RuntimeHelper.downcallHandle(
        "FindNextVolumeW",
        constants$76.FindNextVolumeW$FUNC
    );
    static final FunctionDescriptor FindVolumeClose$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindVolumeClose$MH = RuntimeHelper.downcallHandle(
        "FindVolumeClose",
        constants$76.FindVolumeClose$FUNC
    );
    static final FunctionDescriptor FlushFileBuffers$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FlushFileBuffers$MH = RuntimeHelper.downcallHandle(
        "FlushFileBuffers",
        constants$76.FlushFileBuffers$FUNC
    );
    static final FunctionDescriptor GetDiskFreeSpaceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDiskFreeSpaceA$MH = RuntimeHelper.downcallHandle(
        "GetDiskFreeSpaceA",
        constants$76.GetDiskFreeSpaceA$FUNC
    );
    static final FunctionDescriptor GetDiskFreeSpaceW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDiskFreeSpaceW$MH = RuntimeHelper.downcallHandle(
        "GetDiskFreeSpaceW",
        constants$76.GetDiskFreeSpaceW$FUNC
    );
}


