// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$326 {

    static final FunctionDescriptor wglGetLayerPaletteEntries$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wglGetLayerPaletteEntries$MH = RuntimeHelper.downcallHandle(
        "wglGetLayerPaletteEntries",
        constants$326.wglGetLayerPaletteEntries$FUNC
    );
    static final FunctionDescriptor wglRealizeLayerPalette$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wglRealizeLayerPalette$MH = RuntimeHelper.downcallHandle(
        "wglRealizeLayerPalette",
        constants$326.wglRealizeLayerPalette$FUNC
    );
    static final FunctionDescriptor wglSwapLayerBuffers$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wglSwapLayerBuffers$MH = RuntimeHelper.downcallHandle(
        "wglSwapLayerBuffers",
        constants$326.wglSwapLayerBuffers$FUNC
    );
    static final FunctionDescriptor wglSwapMultipleBuffers$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wglSwapMultipleBuffers$MH = RuntimeHelper.downcallHandle(
        "wglSwapMultipleBuffers",
        constants$326.wglSwapMultipleBuffers$FUNC
    );
    static final FunctionDescriptor WNDPROC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle WNDPROC$MH = RuntimeHelper.downcallHandle(
        constants$326.WNDPROC$FUNC
    );
}


