// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$190 {

    static final FunctionDescriptor EscapeCommFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EscapeCommFunction$MH = RuntimeHelper.downcallHandle(
        "EscapeCommFunction",
        constants$190.EscapeCommFunction$FUNC
    );
    static final FunctionDescriptor GetCommConfig$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCommConfig$MH = RuntimeHelper.downcallHandle(
        "GetCommConfig",
        constants$190.GetCommConfig$FUNC
    );
    static final FunctionDescriptor GetCommMask$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCommMask$MH = RuntimeHelper.downcallHandle(
        "GetCommMask",
        constants$190.GetCommMask$FUNC
    );
    static final FunctionDescriptor GetCommProperties$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCommProperties$MH = RuntimeHelper.downcallHandle(
        "GetCommProperties",
        constants$190.GetCommProperties$FUNC
    );
    static final FunctionDescriptor GetCommModemStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCommModemStatus$MH = RuntimeHelper.downcallHandle(
        "GetCommModemStatus",
        constants$190.GetCommModemStatus$FUNC
    );
    static final FunctionDescriptor GetCommState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCommState$MH = RuntimeHelper.downcallHandle(
        "GetCommState",
        constants$190.GetCommState$FUNC
    );
}


