// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$188 {

    static final FunctionDescriptor PlayMetaFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PlayMetaFile$MH = RuntimeHelper.downcallHandle(
        "PlayMetaFile",
        constants$188.PlayMetaFile$FUNC
    );
    static final FunctionDescriptor PaintRgn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PaintRgn$MH = RuntimeHelper.downcallHandle(
        "PaintRgn",
        constants$188.PaintRgn$FUNC
    );
    static final FunctionDescriptor PolyPolygon$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PolyPolygon$MH = RuntimeHelper.downcallHandle(
        "PolyPolygon",
        constants$188.PolyPolygon$FUNC
    );
    static final FunctionDescriptor PtInRegion$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PtInRegion$MH = RuntimeHelper.downcallHandle(
        "PtInRegion",
        constants$188.PtInRegion$FUNC
    );
    static final FunctionDescriptor PtVisible$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PtVisible$MH = RuntimeHelper.downcallHandle(
        "PtVisible",
        constants$188.PtVisible$FUNC
    );
    static final FunctionDescriptor RectInRegion$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RectInRegion$MH = RuntimeHelper.downcallHandle(
        "RectInRegion",
        constants$188.RectInRegion$FUNC
    );
}


