// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$498 {

    static final FunctionDescriptor RegQueryValueExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueExA$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueExA",
        constants$498.RegQueryValueExA$FUNC
    );
    static final FunctionDescriptor RegQueryValueExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueExW$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueExW",
        constants$498.RegQueryValueExW$FUNC
    );
    static final FunctionDescriptor RegReplaceKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegReplaceKeyA$MH = RuntimeHelper.downcallHandle(
        "RegReplaceKeyA",
        constants$498.RegReplaceKeyA$FUNC
    );
    static final FunctionDescriptor RegReplaceKeyW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegReplaceKeyW$MH = RuntimeHelper.downcallHandle(
        "RegReplaceKeyW",
        constants$498.RegReplaceKeyW$FUNC
    );
    static final FunctionDescriptor RegRestoreKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegRestoreKeyA$MH = RuntimeHelper.downcallHandle(
        "RegRestoreKeyA",
        constants$498.RegRestoreKeyA$FUNC
    );
    static final FunctionDescriptor RegRestoreKeyW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegRestoreKeyW$MH = RuntimeHelper.downcallHandle(
        "RegRestoreKeyW",
        constants$498.RegRestoreKeyW$FUNC
    );
}


