// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$209 {

    static final FunctionDescriptor EndUpdateResourceW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EndUpdateResourceW$MH = RuntimeHelper.downcallHandle(
        "EndUpdateResourceW",
        constants$209.EndUpdateResourceW$FUNC
    );
    static final FunctionDescriptor GlobalAddAtomA$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GlobalAddAtomA$MH = RuntimeHelper.downcallHandle(
        "GlobalAddAtomA",
        constants$209.GlobalAddAtomA$FUNC
    );
    static final FunctionDescriptor GlobalAddAtomW$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GlobalAddAtomW$MH = RuntimeHelper.downcallHandle(
        "GlobalAddAtomW",
        constants$209.GlobalAddAtomW$FUNC
    );
    static final FunctionDescriptor GlobalAddAtomExA$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GlobalAddAtomExA$MH = RuntimeHelper.downcallHandle(
        "GlobalAddAtomExA",
        constants$209.GlobalAddAtomExA$FUNC
    );
    static final FunctionDescriptor GlobalAddAtomExW$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GlobalAddAtomExW$MH = RuntimeHelper.downcallHandle(
        "GlobalAddAtomExW",
        constants$209.GlobalAddAtomExW$FUNC
    );
    static final FunctionDescriptor GlobalFindAtomA$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GlobalFindAtomA$MH = RuntimeHelper.downcallHandle(
        "GlobalFindAtomA",
        constants$209.GlobalFindAtomA$FUNC
    );
}


