// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$591 {

    static final FunctionDescriptor PFN_CERT_STORE_PROV_FIND_CERT$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CERT_STORE_PROV_FIND_CERT$MH = RuntimeHelper.downcallHandle(
        constants$591.PFN_CERT_STORE_PROV_FIND_CERT$FUNC
    );
    static final FunctionDescriptor PFN_CERT_STORE_PROV_FREE_FIND_CERT$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PFN_CERT_STORE_PROV_FREE_FIND_CERT$MH = RuntimeHelper.downcallHandle(
        constants$591.PFN_CERT_STORE_PROV_FREE_FIND_CERT$FUNC
    );
    static final FunctionDescriptor PFN_CERT_STORE_PROV_GET_CERT_PROPERTY$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CERT_STORE_PROV_GET_CERT_PROPERTY$MH = RuntimeHelper.downcallHandle(
        constants$591.PFN_CERT_STORE_PROV_GET_CERT_PROPERTY$FUNC
    );
}


