// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$81 {

    static final FunctionDescriptor PUMS_SCHEDULER_ENTRY_POINT$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PUMS_SCHEDULER_ENTRY_POINT$MH = RuntimeHelper.downcallHandle(
        constants$81.PUMS_SCHEDULER_ENTRY_POINT$FUNC
    );
    static final FunctionDescriptor CreateUmsCompletionList$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateUmsCompletionList$MH = RuntimeHelper.downcallHandle(
        "CreateUmsCompletionList",
        constants$81.CreateUmsCompletionList$FUNC
    );
    static final FunctionDescriptor DequeueUmsCompletionListItems$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DequeueUmsCompletionListItems$MH = RuntimeHelper.downcallHandle(
        "DequeueUmsCompletionListItems",
        constants$81.DequeueUmsCompletionListItems$FUNC
    );
    static final FunctionDescriptor GetUmsCompletionListEvent$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetUmsCompletionListEvent$MH = RuntimeHelper.downcallHandle(
        "GetUmsCompletionListEvent",
        constants$81.GetUmsCompletionListEvent$FUNC
    );
    static final FunctionDescriptor ExecuteUmsThread$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExecuteUmsThread$MH = RuntimeHelper.downcallHandle(
        "ExecuteUmsThread",
        constants$81.ExecuteUmsThread$FUNC
    );
}


