// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$386 {

    static final FunctionDescriptor RegEnumKeyExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegEnumKeyExW$MH = RuntimeHelper.downcallHandle(
        "RegEnumKeyExW",
        constants$386.RegEnumKeyExW$FUNC
    );
    static final FunctionDescriptor RegEnumValueA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegEnumValueA$MH = RuntimeHelper.downcallHandle(
        "RegEnumValueA",
        constants$386.RegEnumValueA$FUNC
    );
    static final FunctionDescriptor RegEnumValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegEnumValueW$MH = RuntimeHelper.downcallHandle(
        "RegEnumValueW",
        constants$386.RegEnumValueW$FUNC
    );
    static final FunctionDescriptor RegFlushKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegFlushKey$MH = RuntimeHelper.downcallHandle(
        "RegFlushKey",
        constants$386.RegFlushKey$FUNC
    );
    static final FunctionDescriptor RegGetKeySecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegGetKeySecurity$MH = RuntimeHelper.downcallHandle(
        "RegGetKeySecurity",
        constants$386.RegGetKeySecurity$FUNC
    );
    static final FunctionDescriptor RegLoadKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegLoadKeyA$MH = RuntimeHelper.downcallHandle(
        "RegLoadKeyA",
        constants$386.RegLoadKeyA$FUNC
    );
}


