// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$93 {

    static final FunctionDescriptor RemoveVectoredContinueHandler$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveVectoredContinueHandler$MH = RuntimeHelper.downcallHandle(
        "RemoveVectoredContinueHandler",
        constants$93.RemoveVectoredContinueHandler$FUNC
    );
    static final FunctionDescriptor RaiseFailFastException$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RaiseFailFastException$MH = RuntimeHelper.downcallHandle(
        "RaiseFailFastException",
        constants$93.RaiseFailFastException$FUNC
    );
    static final FunctionDescriptor FatalAppExitA$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FatalAppExitA$MH = RuntimeHelper.downcallHandle(
        "FatalAppExitA",
        constants$93.FatalAppExitA$FUNC
    );
    static final FunctionDescriptor FatalAppExitW$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FatalAppExitW$MH = RuntimeHelper.downcallHandle(
        "FatalAppExitW",
        constants$93.FatalAppExitW$FUNC
    );
    static final FunctionDescriptor GetThreadErrorMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle GetThreadErrorMode$MH = RuntimeHelper.downcallHandle(
        "GetThreadErrorMode",
        constants$93.GetThreadErrorMode$FUNC
    );
    static final FunctionDescriptor SetThreadErrorMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetThreadErrorMode$MH = RuntimeHelper.downcallHandle(
        "SetThreadErrorMode",
        constants$93.SetThreadErrorMode$FUNC
    );
}


