// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$169 {

    static final FunctionDescriptor DrawEscape$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DrawEscape$MH = RuntimeHelper.downcallHandle(
        "DrawEscape",
        constants$169.DrawEscape$FUNC
    );
    static final FunctionDescriptor Ellipse$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Ellipse$MH = RuntimeHelper.downcallHandle(
        "Ellipse",
        constants$169.Ellipse$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesExA$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesExA",
        constants$169.EnumFontFamiliesExA$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesExW$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesExW",
        constants$169.EnumFontFamiliesExW$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesA$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesA",
        constants$169.EnumFontFamiliesA$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesW$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesW",
        constants$169.EnumFontFamiliesW$FUNC
    );
}


