// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$349 {

    static final FunctionDescriptor ShutdownBlockReasonQuery$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ShutdownBlockReasonQuery$MH = RuntimeHelper.downcallHandle(
        "ShutdownBlockReasonQuery",
        constants$349.ShutdownBlockReasonQuery$FUNC
    );
    static final FunctionDescriptor ShutdownBlockReasonDestroy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ShutdownBlockReasonDestroy$MH = RuntimeHelper.downcallHandle(
        "ShutdownBlockReasonDestroy",
        constants$349.ShutdownBlockReasonDestroy$FUNC
    );
    static final FunctionDescriptor GetCurrentInputMessageSource$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCurrentInputMessageSource$MH = RuntimeHelper.downcallHandle(
        "GetCurrentInputMessageSource",
        constants$349.GetCurrentInputMessageSource$FUNC
    );
    static final FunctionDescriptor GetCIMSSM$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCIMSSM$MH = RuntimeHelper.downcallHandle(
        "GetCIMSSM",
        constants$349.GetCIMSSM$FUNC
    );
    static final FunctionDescriptor GetAutoRotationState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetAutoRotationState$MH = RuntimeHelper.downcallHandle(
        "GetAutoRotationState",
        constants$349.GetAutoRotationState$FUNC
    );
    static final FunctionDescriptor GetDisplayAutoRotationPreferences$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDisplayAutoRotationPreferences$MH = RuntimeHelper.downcallHandle(
        "GetDisplayAutoRotationPreferences",
        constants$349.GetDisplayAutoRotationPreferences$FUNC
    );
}


