// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$871 {

    static final MemorySegment sz_CERT_STORE_PROV_COLLECTION$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Collection");
    static final MemorySegment sz_CERT_STORE_PROV_SYSTEM_REGISTRY_W$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SystemRegistry");
    static final MemorySegment sz_CERT_STORE_PROV_SYSTEM_REGISTRY$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SystemRegistry");
    static final MemorySegment sz_CERT_STORE_PROV_PHYSICAL_W$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Physical");
    static final MemorySegment sz_CERT_STORE_PROV_PHYSICAL$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Physical");
    static final MemorySegment sz_CERT_STORE_PROV_SMART_CARD_W$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SmartCard");
}


