// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$502 {

    static final FunctionDescriptor RegGetValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegGetValueW$MH = RuntimeHelper.downcallHandle(
        "RegGetValueW",
        constants$502.RegGetValueW$FUNC
    );
    static final FunctionDescriptor RegCopyTreeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegCopyTreeW$MH = RuntimeHelper.downcallHandle(
        "RegCopyTreeW",
        constants$502.RegCopyTreeW$FUNC
    );
    static final FunctionDescriptor RegLoadMUIStringA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegLoadMUIStringA$MH = RuntimeHelper.downcallHandle(
        "RegLoadMUIStringA",
        constants$502.RegLoadMUIStringA$FUNC
    );
    static final FunctionDescriptor RegLoadMUIStringW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegLoadMUIStringW$MH = RuntimeHelper.downcallHandle(
        "RegLoadMUIStringW",
        constants$502.RegLoadMUIStringW$FUNC
    );
    static final FunctionDescriptor RegLoadAppKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegLoadAppKeyA$MH = RuntimeHelper.downcallHandle(
        "RegLoadAppKeyA",
        constants$502.RegLoadAppKeyA$FUNC
    );
    static final FunctionDescriptor RegLoadAppKeyW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegLoadAppKeyW$MH = RuntimeHelper.downcallHandle(
        "RegLoadAppKeyW",
        constants$502.RegLoadAppKeyW$FUNC
    );
}


