// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$815 {

    static final MemoryAddress OCSP_RESPONSE$ADDR = MemoryAddress.ofLong(67L);
    static final MemoryAddress OCSP_BASIC_SIGNED_RESPONSE$ADDR = MemoryAddress.ofLong(68L);
    static final MemoryAddress OCSP_BASIC_RESPONSE$ADDR = MemoryAddress.ofLong(69L);
    static final MemoryAddress X509_LOGOTYPE_EXT$ADDR = MemoryAddress.ofLong(70L);
    static final MemoryAddress X509_BIOMETRIC_EXT$ADDR = MemoryAddress.ofLong(71L);
    static final MemoryAddress CNG_RSA_PUBLIC_KEY_BLOB$ADDR = MemoryAddress.ofLong(72L);
}


