// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$580 {

    static final FunctionDescriptor CryptMsgControl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgControl$MH = RuntimeHelper.downcallHandle(
        "CryptMsgControl",
        constants$580.CryptMsgControl$FUNC
    );
    static final FunctionDescriptor CryptMsgVerifyCountersignatureEncoded$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgVerifyCountersignatureEncoded$MH = RuntimeHelper.downcallHandle(
        "CryptMsgVerifyCountersignatureEncoded",
        constants$580.CryptMsgVerifyCountersignatureEncoded$FUNC
    );
    static final FunctionDescriptor CryptMsgVerifyCountersignatureEncodedEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgVerifyCountersignatureEncodedEx$MH = RuntimeHelper.downcallHandle(
        "CryptMsgVerifyCountersignatureEncodedEx",
        constants$580.CryptMsgVerifyCountersignatureEncodedEx$FUNC
    );
    static final FunctionDescriptor CryptMsgCountersign$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgCountersign$MH = RuntimeHelper.downcallHandle(
        "CryptMsgCountersign",
        constants$580.CryptMsgCountersign$FUNC
    );
    static final FunctionDescriptor CryptMsgCountersignEncoded$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgCountersignEncoded$MH = RuntimeHelper.downcallHandle(
        "CryptMsgCountersignEncoded",
        constants$580.CryptMsgCountersignEncoded$FUNC
    );
    static final FunctionDescriptor PFN_CMSG_ALLOC$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
}


