// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$510 {

    static final FunctionDescriptor SetPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetPrinterW$MH = RuntimeHelper.downcallHandle(
        "SetPrinterW",
        constants$510.SetPrinterW$FUNC
    );
    static final FunctionDescriptor GetPrinterA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPrinterA$MH = RuntimeHelper.downcallHandle(
        "GetPrinterA",
        constants$510.GetPrinterA$FUNC
    );
    static final FunctionDescriptor GetPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPrinterW$MH = RuntimeHelper.downcallHandle(
        "GetPrinterW",
        constants$510.GetPrinterW$FUNC
    );
    static final FunctionDescriptor AddPrinterDriverA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddPrinterDriverA$MH = RuntimeHelper.downcallHandle(
        "AddPrinterDriverA",
        constants$510.AddPrinterDriverA$FUNC
    );
    static final FunctionDescriptor AddPrinterDriverW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddPrinterDriverW$MH = RuntimeHelper.downcallHandle(
        "AddPrinterDriverW",
        constants$510.AddPrinterDriverW$FUNC
    );
    static final FunctionDescriptor AddPrinterDriverExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle AddPrinterDriverExA$MH = RuntimeHelper.downcallHandle(
        "AddPrinterDriverExA",
        constants$510.AddPrinterDriverExA$FUNC
    );
}


