// Generated by jextract

package app.cleancode.bindings.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class tagPOINTFX {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("fract"),
            Constants$root.C_SHORT$LAYOUT.withName("value")
        ).withName("x"),
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("fract"),
            Constants$root.C_SHORT$LAYOUT.withName("value")
        ).withName("y")
    ).withName("tagPOINTFX");
    public static MemoryLayout $LAYOUT() {
        return tagPOINTFX.$struct$LAYOUT;
    }
    public static MemorySegment x$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static MemorySegment y$slice(MemorySegment seg) {
        return seg.asSlice(4, 4);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


